# .settings contains all settings related to the project and it's building of
# assets, themes and files.

# public contains settings related to the directory used for public assets which
# will be built and servable using the generated package.

app = "ui"
package = "github.com/utronframework/play/ui"

[static]
indexDir = "./public" # sets where index.html will be located
jsFile = "ui_app_bundle.js"
jsMapFile = "ui_app_bundle.js.map"

[public]
path = "./public"
packageName = "ui"

[theme]
PrimaryBrandColor = "#222222"
SecondaryBrandColor = "#444444"
